services:
  - type: web
    name: apex-phishing-server
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_OPTIONS
        value: "--tls-min-v1.2 --max-old-space-size=512"
      - key: MONGODB_URI
        sync: false